version: '3.7'

services:
  collector:
    build: ./collector
    networks:
      - app_net

  db:
    build: ./postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - PGHOST=/tmp # Apparently very important for accessing from pgadmin
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=db
      - PG_MODE=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=postgres
      - PG_PRIMARY_PASSWORD=postgres
      - PG_ROOT_PASSWORD=postgres
      - PGPASSWORD=postgres
      - PGCONNECT_TIMEOUT=60
      - MODE=postgres
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
    volumes:
      - ./postgres/pgconf/:/pgconf
    ports:
      - "5432:5432"
    networks:
      - app_net

networks:
  app_net: