FROM crunchydata/crunchy-postgres:centos8-13.6-4.7.5

COPY ./pgconf/table.sql /pgconf/table.sql
COPY ./pgconf/data.sql /pgconf/data.sql
COPY ./pgconf/setup.sql /pgconf/setup.sql


#RUN cat ./pgconf/table.sql >> /pgconf/setup.sql
#RUN cat ./pgconf/data.sql >> /pgconf/setup.sql


